name = "mulyono"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "edbfff67-6385-4f0a-a19a-f708bc307bbf"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
